version: "2"

services:
  muchas:
    build: .
    environment:
    - NODE_ENV
    - DEBUG_PORT
    - DATABASE_URI
    volumes:
      - .:/app
    ports:
      - 6028:6028
      - 6029:6029
      - 9000:9000
    networks:
      - muchas
    command: npm run start:it
  # MongoDB
  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - /data/db
    ports:
      - 27017:27017
    networks:
      - muchas
  # RabbitMQ
  rabbit:
    image: rabbitmq:3.7-management
    logging:
      driver: none
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - muchas
networks:
  muchas:
    driver: bridge